//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LithologyLog.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LithologyLog.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil etmə paneli.
        /// </summary>
        public static string AddedPanel {
            get {
                return ResourceManager.GetString("AddedPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu təşkilat artıq mövcutdur.
        /// </summary>
        public static string AleadyTakenOrganization {
            get {
                return ResourceManager.GetString("AleadyTakenOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istifadəçi artıq mövcutdur.
        /// </summary>
        public static string AleadyTakenUsername {
            get {
                return ResourceManager.GetString("AleadyTakenUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçinin hesabınız bloklanıb.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağla.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktif.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktə paneli.
        /// </summary>
        public static string EditPanel {
            get {
                return ResourceManager.GetString("EditPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron poçt ünvanı.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeta baş verdi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız 5 dəqiqə müddətində bloklanıb.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə nömrəsi.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün xanalar doldurulmalıdır.
        /// </summary>
        public static string ModelNotValid {
            get {
                return ResourceManager.GetString("ModelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi tapılmadı.
        /// </summary>
        public static string NotFoundUser {
            get {
                return ResourceManager.GetString("NotFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təşkilatların siyahısı.
        /// </summary>
        public static string OrganizationList {
            get {
                return ResourceManager.GetString("OrganizationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu sahə məcburi xanadır.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qısa adı.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əməliyyat uğurla yerinə yetirildi.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÖEN.
        /// </summary>
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlıq.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilərin siyahısı.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilər.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə yanlışdır.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
